### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by briancmills** [joshuadavy/Project-Repo#1]
Implement a command-line utility that supports converting from Fahrenheit to Celsius temperature. 

- Support very basic natural language processing, by that I mean if a user types in 72F you would finger the output should be converted to celsius. 
- If the user just types a number, prompt them for which system they are converting from. 
- Sanitize the text input, if someone types in garbage the system should handle that and produce a meaningful error message. 

The formula for the conversion is: `(32°F − 32) × 5/9 = 0°C`

**Comment by joshuadavy** [comment]
I uploaded a program that: Converts a temperature from Fahrenheit to Celsius and prompts what system the temperature was from and processes accordingly. However, I do not know how to approach the last issue on this list, I will continue to work on making an error message.
